//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevToolbox.Wpf.Demo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevToolbox.Wpf.Demo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Field.
        /// </summary>
        internal static string Add_Field {
            get {
                return ResourceManager.GetString("Add_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add File....
        /// </summary>
        internal static string Add_File {
            get {
                return ResourceManager.GetString("Add_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Address.
        /// </summary>
        internal static string Add_New_Address {
            get {
                return ResourceManager.GetString("Add_New_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Photo.
        /// </summary>
        internal static string Add_Photo {
            get {
                return ResourceManager.GetString("Add_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIM.
        /// </summary>
        internal static string AIM {
            get {
                return ResourceManager.GetString("AIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All completed reminders will be permanently deleted. You cannot undo this action..
        /// </summary>
        internal static string All_completed_reminders_will_be_permanently_deleted_You_cannot_undo_this_action {
            get {
                return ResourceManager.GetString("All_completed_reminders_will_be_permanently_deleted_You_cannot_undo_this_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Contacts.
        /// </summary>
        internal static string All_Contacts {
            get {
                return ResourceManager.GetString("All_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all-day.
        /// </summary>
        internal static string all_day {
            get {
                return ResourceManager.GetString("all_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All of its reminders will be permanently deleted..
        /// </summary>
        internal static string All_of_its_reminders_will_be_permanently_deleted {
            get {
                return ResourceManager.GetString("All_of_its_reminders_will_be_permanently_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM.
        /// </summary>
        internal static string AM {
            get {
                return ResourceManager.GetString("AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anniversary.
        /// </summary>
        internal static string Anniversary {
            get {
                return ResourceManager.GetString("Anniversary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple ID.
        /// </summary>
        internal static string Apple_ID {
            get {
                return ResourceManager.GetString("Apple_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple Watch.
        /// </summary>
        internal static string Apple_Watch {
            get {
                return ResourceManager.GetString("Apple_Watch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected contact?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_delete_the_selected_contact {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_delete_the_selected_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected group?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_delete_the_selected_group {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_delete_the_selected_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant.
        /// </summary>
        internal static string Assistant {
            get {
                return ResourceManager.GetString("Assistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attachments.
        /// </summary>
        internal static string attachments {
            get {
                return ResourceManager.GetString("attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication error.
        /// </summary>
        internal static string Authentication_error {
            get {
                return ResourceManager.GetString("Authentication_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        internal static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brother.
        /// </summary>
        internal static string Brother {
            get {
                return ResourceManager.GetString("Brother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete &quot;{0}&quot;..
        /// </summary>
        internal static string Can_t_delete_item {
            get {
                return ResourceManager.GetString("Can_t_delete_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        internal static string Child {
            get {
                return ResourceManager.GetString("Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Photo....
        /// </summary>
        internal static string Choose_Photo {
            get {
                return ResourceManager.GetString("Choose_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all completed reminders?.
        /// </summary>
        internal static string Clear_all_completed_reminders {
            get {
                return ResourceManager.GetString("Clear_all_completed_reminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Completed.
        /// </summary>
        internal static string Clear_Completed {
            get {
                return ResourceManager.GetString("Clear_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country or Region.
        /// </summary>
        internal static string Country_or_Region {
            get {
                return ResourceManager.GetString("Country_or_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Contact.
        /// </summary>
        internal static string Delete_Contact {
            get {
                return ResourceManager.GetString("Delete_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Event.
        /// </summary>
        internal static string Delete_Event {
            get {
                return ResourceManager.GetString("Delete_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete &quot;{0}&quot;?.
        /// </summary>
        internal static string Delete_Item {
            get {
                return ResourceManager.GetString("Delete_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete List.
        /// </summary>
        internal static string Delete_List {
            get {
                return ResourceManager.GetString("Delete_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Group.
        /// </summary>
        internal static string Empty_Group {
            get {
                return ResourceManager.GetString("Empty_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End on a Date.
        /// </summary>
        internal static string End_on_a_Date {
            get {
                return ResourceManager.GetString("End_on_a_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Title.
        /// </summary>
        internal static string Event_Title {
            get {
                return ResourceManager.GetString("Event_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 2 Weeks.
        /// </summary>
        internal static string Every_2_Weeks {
            get {
                return ResourceManager.GetString("Every_2_Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Day.
        /// </summary>
        internal static string Every_Day {
            get {
                return ResourceManager.GetString("Every_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Month.
        /// </summary>
        internal static string Every_Month {
            get {
                return ResourceManager.GetString("Every_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Week.
        /// </summary>
        internal static string Every_Week {
            get {
                return ResourceManager.GetString("Every_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Year.
        /// </summary>
        internal static string Every_Year {
            get {
                return ResourceManager.GetString("Every_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Message.
        /// </summary>
        internal static string Exception_message {
            get {
                return ResourceManager.GetString("Exception_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export vCard....
        /// </summary>
        internal static string Export_vCard {
            get {
                return ResourceManager.GetString("Export_vCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        internal static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father.
        /// </summary>
        internal static string Father {
            get {
                return ResourceManager.GetString("Father", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flickr.
        /// </summary>
        internal static string Flickr {
            get {
                return ResourceManager.GetString("Flickr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend.
        /// </summary>
        internal static string Friend {
            get {
                return ResourceManager.GetString("Friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        internal static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gadu-Gadu.
        /// </summary>
        internal static string Gadu_Gadu {
            get {
                return ResourceManager.GetString("Gadu_Gadu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Date....
        /// </summary>
        internal static string Go_To_Date {
            get {
                return ResourceManager.GetString("Go_To_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Today.
        /// </summary>
        internal static string Go_to_Today {
            get {
                return ResourceManager.GetString("Go_to_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to today.
        /// </summary>
        internal static string Go_to_today_button {
            get {
                return ResourceManager.GetString("Go_to_today_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Talk.
        /// </summary>
        internal static string Google_Talk {
            get {
                return ResourceManager.GetString("Google_Talk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Fax.
        /// </summary>
        internal static string Home_Fax {
            get {
                return ResourceManager.GetString("Home_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        internal static string Home_Page {
            get {
                return ResourceManager.GetString("Home_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iCloud.
        /// </summary>
        internal static string iCloud {
            get {
                return ResourceManager.GetString("iCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iCloud - Print.
        /// </summary>
        internal static string iCloud_Print {
            get {
                return ResourceManager.GetString("iCloud_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICQ.
        /// </summary>
        internal static string ICQ {
            get {
                return ResourceManager.GetString("ICQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import vCard....
        /// </summary>
        internal static string Import_vCard {
            get {
                return ResourceManager.GetString("Import_vCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant Message.
        /// </summary>
        internal static string Instant_Message {
            get {
                return ResourceManager.GetString("Instant_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invitees.
        /// </summary>
        internal static string invitees {
            get {
                return ResourceManager.GetString("invitees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone.
        /// </summary>
        internal static string iPhone {
            get {
                return ResourceManager.GetString("iPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jabber.
        /// </summary>
        internal static string Jabber {
            get {
                return ResourceManager.GetString("Jabber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        internal static string Job_Title {
            get {
                return ResourceManager.GetString("Job_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkedIn.
        /// </summary>
        internal static string LinkedIn {
            get {
                return ResourceManager.GetString("LinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List color.
        /// </summary>
        internal static string List_color {
            get {
                return ResourceManager.GetString("List_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make This My Card.
        /// </summary>
        internal static string Make_This_My_Card {
            get {
                return ResourceManager.GetString("Make_This_My_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle.
        /// </summary>
        internal static string Middle {
            get {
                return ResourceManager.GetString("Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother.
        /// </summary>
        internal static string Mother {
            get {
                return ResourceManager.GetString("Mother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSN.
        /// </summary>
        internal static string MSN {
            get {
                return ResourceManager.GetString("MSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myspace.
        /// </summary>
        internal static string Myspace {
            get {
                return ResourceManager.GetString("Myspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never Repeat.
        /// </summary>
        internal static string Never_Repeat {
            get {
                return ResourceManager.GetString("Never_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Calendar.
        /// </summary>
        internal static string New_Calendar {
            get {
                return ResourceManager.GetString("New_Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Contact.
        /// </summary>
        internal static string New_Contact {
            get {
                return ResourceManager.GetString("New_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Event.
        /// </summary>
        internal static string New_Event {
            get {
                return ResourceManager.GetString("New_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Group.
        /// </summary>
        internal static string New_Group {
            get {
                return ResourceManager.GetString("New_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New item....
        /// </summary>
        internal static string New_item {
            get {
                return ResourceManager.GetString("New_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New List.
        /// </summary>
        internal static string New_List {
            get {
                return ResourceManager.GetString("New_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        internal static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «{0}».
        /// </summary>
        internal static string Nickname_Format {
            get {
                return ResourceManager.GetString("Nickname_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Contact Selected.
        /// </summary>
        internal static string No_Contact_Selected {
            get {
                return ResourceManager.GetString("No_Contact_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Events.
        /// </summary>
        internal static string No_Events {
            get {
                return ResourceManager.GetString("No_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Name.
        /// </summary>
        internal static string No_Name {
            get {
                return ResourceManager.GetString("No_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reminder list selected.
        /// </summary>
        internal static string No_reminder_list_selected {
            get {
                return ResourceManager.GetString("No_reminder_list_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found.
        /// </summary>
        internal static string No_results_found {
            get {
                return ResourceManager.GetString("No_results_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search results.
        /// </summary>
        internal static string No_search_results {
            get {
                return ResourceManager.GetString("No_search_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to note.
        /// </summary>
        internal static string note {
            get {
                return ResourceManager.GetString("note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note (optional).
        /// </summary>
        internal static string Note_optional {
            get {
                return ResourceManager.GetString("Note_optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On a day.
        /// </summary>
        internal static string On_a_day {
            get {
                return ResourceManager.GetString("On_a_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pager.
        /// </summary>
        internal static string Pager {
            get {
                return ResourceManager.GetString("Pager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        internal static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner.
        /// </summary>
        internal static string Partner {
            get {
                return ResourceManager.GetString("Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        internal static string Personalization {
            get {
                return ResourceManager.GetString("Personalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonetic Company Name.
        /// </summary>
        internal static string Phonetic_Company_Name {
            get {
                return ResourceManager.GetString("Phonetic_Company_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonetic First Name.
        /// </summary>
        internal static string Phonetic_First_Name {
            get {
                return ResourceManager.GetString("Phonetic_First_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonetic Last Name.
        /// </summary>
        internal static string Phonetic_Last_Name {
            get {
                return ResourceManager.GetString("Phonetic_Last_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait....
        /// </summary>
        internal static string Please_Wait {
            get {
                return ResourceManager.GetString("Please_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM.
        /// </summary>
        internal static string PM {
            get {
                return ResourceManager.GetString("PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        internal static string Postal_Code {
            get {
                return ResourceManager.GetString("Postal_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences....
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        internal static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QQ.
        /// </summary>
        internal static string QQ {
            get {
                return ResourceManager.GetString("QQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Contacts.
        /// </summary>
        internal static string Refresh_Contacts {
            get {
                return ResourceManager.GetString("Refresh_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related People.
        /// </summary>
        internal static string Related_People {
            get {
                return ResourceManager.GetString("Related_People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind me.
        /// </summary>
        internal static string Remind_me {
            get {
                return ResourceManager.GetString("Remind_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminders.
        /// </summary>
        internal static string Reminders {
            get {
                return ResourceManager.GetString("Reminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Completed.
        /// </summary>
        internal static string Reminders_completed {
            get {
                return ResourceManager.GetString("Reminders_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Group.
        /// </summary>
        internal static string Rename_Group {
            get {
                return ResourceManager.GetString("Rename_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repeat.
        /// </summary>
        internal static string repeat {
            get {
                return ResourceManager.GetString("repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results for “{0}”.
        /// </summary>
        internal static string Results_for {
            get {
                return ResourceManager.GetString("Results_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes to &quot;{0}&quot;?.
        /// </summary>
        internal static string Save_Changes_to {
            get {
                return ResourceManager.GetString("Save_Changes_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School.
        /// </summary>
        internal static string School {
            get {
                return ResourceManager.GetString("School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search {0}.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search all reminders.
        /// </summary>
        internal static string Search_all_reminders {
            get {
                return ResourceManager.GetString("Search_all_reminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string Select_All {
            get {
                return ResourceManager.GetString("Select_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Declined Events.
        /// </summary>
        internal static string Show_Declined_Events {
            get {
                return ResourceManager.GetString("Show_Declined_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with Apple ID.
        /// </summary>
        internal static string Sign_in_with_Apple_ID {
            get {
                return ResourceManager.GetString("Sign_in_with_Apple_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string Sign_out {
            get {
                return ResourceManager.GetString("Sign_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SinaWeibo.
        /// </summary>
        internal static string Sina_Weibo {
            get {
                return ResourceManager.GetString("Sina_Weibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sister.
        /// </summary>
        internal static string Sister {
            get {
                return ResourceManager.GetString("Sister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype.
        /// </summary>
        internal static string Skype {
            get {
                return ResourceManager.GetString("Skype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spouse.
        /// </summary>
        internal static string Spouse {
            get {
                return ResourceManager.GetString("Spouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace.
        /// </summary>
        internal static string Stack_Trace {
            get {
                return ResourceManager.GetString("Stack_Trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix.
        /// </summary>
        internal static string Suffix {
            get {
                return ResourceManager.GetString("Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Contacts.
        /// </summary>
        internal static string Total_Contacts {
            get {
                return ResourceManager.GetString("Total_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        internal static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception.
        /// </summary>
        internal static string Unhandled_exception {
            get {
                return ResourceManager.GetString("Unhandled_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled Group.
        /// </summary>
        internal static string Untitled_Group {
            get {
                return ResourceManager.GetString("Untitled_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to url.
        /// </summary>
        internal static string url {
            get {
                return ResourceManager.GetString("url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string URL_Upper {
            get {
                return ResourceManager.GetString("URL_Upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string User_name {
            get {
                return ResourceManager.GetString("User_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        internal static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Fax.
        /// </summary>
        internal static string Work_Fax {
            get {
                return ResourceManager.GetString("Work_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yahoo.
        /// </summary>
        internal static string Yahoo {
            get {
                return ResourceManager.GetString("Yahoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must own at least one reminder list. Create a new list and then delete this one..
        /// </summary>
        internal static string You_must_own_at_least_one_reminder_list_Create_a_new_list_and_then_delete_this_one {
            get {
                return ResourceManager.GetString("You_must_own_at_least_one_reminder_list_Create_a_new_list_and_then_delete_this_on" +
                        "e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes will be lost if you don&apos;t save them..
        /// </summary>
        internal static string Your_changes_will_be_lost_if_you_don_t_save_them {
            get {
                return ResourceManager.GetString("Your_changes_will_be_lost_if_you_don_t_save_them", resourceCulture);
            }
        }
    }
}
